### ISSUE TITLE
NetRexx Pipelines specs issue

### ISSUE THREAD

**Issue by remesm** [RexxLA/NetRexx#44]
Examples says it all. 
specs seems to get lost when going out of range.

$ pipe 'literal 123 | specs 1-10 1 |  cons '
123
$ pipe 'literal 123 | specs 2-10 1 |  cons '
23
$ pipe 'literal 123 | specs 3-10 1 |  cons '
3
$ pipe 'literal 123 | specs 4-10 1 |  cons '

$ pipe 'literal 123 | specs 5-10 1 |  cons '
netrexx.lang.BadArgumentException: Argument -1 < 0
    at netrexx.lang.Rexx.intcheck(Rexx.java:920)
    at netrexx.lang.Rexx.substr(Rexx.java:1458)
    at netrexx.lang.Rexx.substr(Rexx.java:1452)
    at p5e8377b_specs_2.run(p5e8377b.java:173)
    at org.netrexx.njpipes.pipes.ThreadPool.run(ThreadPool.java:76)
    at java.base/java.lang.Thread.run(Thread.java:1589)
ThreadQ Thread[#27,Thread-1,5,njPipes]
ThreadQ Thread[#27,Thread-1,5,njPipes]
Exiting due to uncaught Exception Argument -1 < 0
ThreadQ Thread[#27,Thread-1,5,njPipes]
Exiting due to uncaught Exception Argument -1 < 0
ThreadQ Thread[#29,Thread-3,5,njPipes]
Exiting due to uncaught Exception Argument -1 < 0
ThreadQ Thread[#29,Thread-3,5,njPipes]
ThreadQ Thread[#29,Thread-3,5,njPipes]

**Comment by remesm** [comment]
Fixed by Jeff with commit dbdcefb05009ed5ea03806150233e36c1b7a7ea3
