### ISSUE TITLE
Execution error: nrc -exec rexxcps.nrx

### ISSUE THREAD

**Issue by jlfaucher** [RexxLA/NetRexx#63]
Tested with NetRexx-4.06-GA

`nrc -exec rexxcps.nrx `

raises

```
NetRexx portable processor 4.06-GA build 152-20240304-0612
Copyright (c) RexxLA, 2011,2024.   All rights reserved.
Parts Copyright (c) IBM Corporation, 1995,2008.
Program rexxcps.nrx
    function subroutine(Rexx,Rexx)
    function formatThousands(Rexx)
===== Exec: rexxcps =====
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "netrexx.lang.Rexx.toCharArray()" because "<parameter1>" is null
	at netrexx.lang.RexxParse.parse(RexxParse.java:116)
	at org.netrexx.process.NrParse.interpret(NrParse.java:598)
	at org.netrexx.process.RxInterpreter.runfree(RxInterpreter.java:1323)
	at org.netrexx.process.RxInterpreter.callMethod(RxInterpreter.java:1169)
	at org.netrexx.process.RxInterpreter.callMethod(RxInterpreter.java:824)
	at org.netrexx.process.RxTranslator.exec(RxTranslator.java:806)
	at org.netrexx.process.NetRexxC.process(NetRexxC.java:553)
	at org.netrexx.process.NetRexxC.main2(NetRexxC.java:360)
	at org.netrexx.process.NetRexxC.main2(NetRexxC.java:339)
	at org.netrexx.process.NetRexxC.main2(NetRexxC.java:335)
	at org.netrexx.process.NetRexxC.main(NetRexxC.java:180)

```

No error with this sequence:
```
nrc rexxcps.nrx
java rexxcps

```

**Comment by remesm** [comment]
Can you attach rexxcps.nrx?
Thanks

**Comment by jlfaucher** [comment]
Github does not allow file attachment with nrx suffix.
Added .txt
[rexxcps.nrx.txt](https://github.com/user-attachments/files/16013392/rexxcps.nrx.txt)
This file is located in the "examples" directory.

**Comment by rvjansen** [comment]
Chapeau!

Is this fixable or do we need to document it for interpreted execution?

best regards,

René.

**Comment by jlfaucher** [comment]
Thanks!

I get these numbers on my laptop:
```
18_407_194_702_387 NetRexx clauses per second        -- netrexx compiled
   302_886_536_330 NetRexx clauses per second        -- netrexx interpreted
        23_736_393 REXX clauses per second           -- oorexx
```

The difference with oorexx is stunning...
After comparing the sources, I think there is an error in rexxcps.nrx
I will create another ticket for that.

**Comment by rvjansen** [comment]
Hi Jean-Louis,

we cannot change CPS, ever. We cannot repeat old measurements which go back to the early eighties.
The case with NetRexx is that the JVM JIT eliminates a number of calls when the output is not used. Apart from that, it is faster whenever it compiles fragments of code to native.

There is a NetRexx version - by MFC - which is in the repository as nrxcps.nrx and there is a presentation which discusses some of these phenomena: https://www.rexxla.org/presentations/2019/cps2019.pdf "30 years of CPS".

I am open for working on a "new generation CPS"; but the classic one is what it is.

best regards,

René.

**Comment by remesm** [comment]
Can be closed, fixed in commit [fa8de7]

**Comment by rvjansen** [comment]
fixed, tested and closed
